// ncamp-todo-vue/src/App.vue
<template>
  <div id="app">

    <template v-if="!usernameEntered">
      <UserInput
        :username="username"
        @updateUsername="username = $event.target.value"
        @saveUsername="usernameEntered = true"
      />
    </template>

    <template v-else>
      <UserOutput
        :username="username"
      />
      <TodoList
        :todos="todos"
        @storeTodo="todo = $event.target.value"
        @addTodo="todos.push(todo)"
        @removeTodo="todos.splice(todos.indexOf($event), 1);"
      />
    </template>

  </div>
</template>

<script>
import UserInput from './components/UserInput.vue';
import UserOutput from './components/UserOutput.vue';
import TodoList from './components/TodoList.vue';

export default {
  name: 'app',

  components: {
    UserInput,
    UserOutput,
    TodoList
  },

  data() {
    return {
      username: 'Thomas',

      usernameEntered: false,

      todo: '',

      todos: ['Do good things', 'Talk about it'],
    }
  },
}
</script>

<style>
#app {
  border: 1px solid black;
  border-radius: 20px;
  box-shadow: 2px 2px 2px gray;
  color: #2c3e50;
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  margin: 60px auto;
  padding-bottom: 10px;
  text-align: center;
  width: 400px;
}
</style>

// ncamp-todo-react/src/App.js
import React, { Component } from 'react';
import './App.css';

import UserInput from './UserInput/UserInput';
import UserOutput from './UserOutput/UserOutput';
import TodoList from './TodoList/TodoList';

class App extends Component {
  state = {
    username: 'Thomas',

    usernameEntered: false,

    todo: '',

    todos: ['Do good things', 'Talk about it'],
  }

  updateUsername = ({target}) => {
    const username = target.value;

    this.setState({username});
  }

  saveUsername = () => {
    this.setState({
      usernameEntered: true
    })
  }

  storeTodo = ({target}) => {
    const todo = target.value;

    this.setState({todo});
  }

  addTodo = () => {
    const todos = [...this.state.todos, this.state.todo];

    this.setState({todos});
  }

  removeTodo = (todo) => {
    const todos = [...this.state.todos];
    
    todos.splice(this.state.todos.indexOf(todo), 1);

    this.setState({todos});
  }

  render() {
    return (
      <div className="App">

        {!this.state.usernameEntered
          ?
            <UserInput
              username={this.state.username}
              onChangeInput={this.updateUsername}
              onClickButton={this.saveUsername}
            />
          :
            <div>
              <UserOutput
                username={this.state.username}
              />
  
              <TodoList
                todos={this.state.todos}
                onChangeInput={this.storeTodo}
                onClickButton={this.addTodo}
                onClickTodo={this.removeTodo}
              />
            </div>
        }
      </div>
    );
  }
}

export default App;
