// ncamp-todo-react/src/App.js
import React, { Component } from 'react';
import './App.css';

import UserInput from './UserInput/UserInput';
import UserOutput from './UserOutput/UserOutput';
import TodoList from './TodoList/TodoList';

class App extends Component {
  state = {
    username: 'Thomas',

    usernameEntered: false,

    todo: '',

    todos: ['Do good things', 'Talk about it'],
  }

  updateUsername = ({target}) => {
    const username = target.value;

    this.setState({username});
  }

  saveUsername = () => {
    this.setState({
      usernameEntered: true
    })
  }

  storeTodo = ({target}) => {
    const todo = target.value;

    this.setState({todo});
  }

  addTodo = () => {
    const todos = [...this.state.todos, this.state.todo];

    this.setState({todos});
  }

  removeTodo = (todo) => {
    const todos = [...this.state.todos];
    
    todos.splice(this.state.todos.indexOf(todo), 1);

    this.setState({todos});
  }

  render() {
    return (
      <div className="App">

        {!this.state.usernameEntered
          ?
            <UserInput
              username={this.state.username}
              onChangeInput={this.updateUsername}
              onClickButton={this.saveUsername}
            />
          :
            <div>
              <UserOutput
                username={this.state.username}
              />
  
              <TodoList
                todos={this.state.todos}
                onChangeInput={this.storeTodo}
                onClickButton={this.addTodo}
                onClickTodo={this.removeTodo}
              />
            </div>
        }
      </div>
    );
  }
}

export default App;

// ncamp-todo-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
  username: string = 'Thomas';

  usernameEntered: boolean = false;

  todo: string = '';
  
  todos: string[] = ['Do good things', 'Talk about it'];

  changeUsername(name: string): void {
    this.username = name;
  }

  saveUsername(): void {
    this.usernameEntered = true;
  }

  storeTodo(todo: string): void {
    this.todo = todo;
  }

  addTodo(): void {
    this.todos.push(this.todo);
  }

  removeTodo(todo: string): void {
    this.todos.splice(this.todos.indexOf(todo), 1);
  }
}

<app-user-input
    [username]="username"
    (onChangeUsername)="changeUsername($event)"
    (onSaveUsername)="saveUsername()"
    *ngIf="!usernameEntered; else isEntered"
></app-user-input>

<ng-template #isEntered>
    <app-user-output [username]="username"></app-user-output>
    <app-todo-list
        [todos]="todos"
        (onStoreTodo)="storeTodo($event)"
        (onAddTodo)="addTodo()"
        (onRemoveTodo)="removeTodo($event)"
    ></app-todo-list>
</ng-template>
