// ncamp-todo-react/src/TodoList/TodoList.js
import React from 'react';

import TodoItem from './TodoItem/TodoItem';

const TodoList = (props) => {
    const items = props.todos.map((todo, i) => (
        <TodoItem todo={todo} onClickItem={props.onClickTodo} key={i}/>
    ));

    return (
        <div>
            <input onChange={props.onChangeInput} />
            <button onClick={props.onClickButton}>
                Add Todo
            </button>
            <ul>{items}</ul>
        </div>
    );
};

export default TodoList;

// ncamp-todo-vue/src/components/TodoList.vue
<template>
    <div>
        <input @input="$emit('storeTodo', $event)" />
        <button @click="$emit('addTodo')">
            Add Todo
        </button>
        <ul>
            <TodoItem
                v-for="(todo, i) in todos"
                :todo="todo"
                :index="i"
                :key="i"
                @removeItem="$emit('removeTodo', todo)"
            />
        </ul>
    </div>
</template>

<script>
import TodoItem from './TodoItem.vue';

export default {
    name: 'TodoList',
    
    components: {
        TodoItem
    },

    props: {
        todos: Array
    },
}
</script>
