// ncamp-todo-angular/src/app/user-input/user-input.component.ts
import { Component, Input, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-user-input',
  templateUrl: './user-input.component.html'
})
export class UserInputComponent {

  @Input() username: string;

  @Output() onChangeUsername = new EventEmitter<string>();
  @Output() onSaveUsername = new EventEmitter();

  onChange(username: string): void {
    this.onChangeUsername.emit(username);
  }

  onClick(): void {
    this.onSaveUsername.emit();
  }
}

<p>Input your name:</p>
<input [value]="username" (input)="onChange($event.target.value)">
<button (click)="onClick()">Save name</button>

// ncamp-todo-vue/src/components/UserInput.vue
<template>
    <div>
        <p>Input your name:</p>
        <input :value="username" @input="$emit('updateUsername', $event)" />
        <button @click="$emit('saveUsername', $event)">Save name</button>
    </div>
</template>

<script>
export default {
    name: 'UserInput',
    
    props: {
        username: String
    }   
}
</script>
